import type { Metadata } from "next"
import { Inter, Playfair_Display } from "next/font/google"

import "../globals.css"

import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin"
import { extractRouterConfig } from "uploadthing/server"

import { Toaster } from "~/components/ui/sonner"
import { Provider } from "~/lib/providers"
import { cn } from "~/lib/utils"
import { ourFileRouter } from "./api/uploadthing/core"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-serif",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es">
      <body
        className={cn(
          "bg-background font-sans antialiased",
          inter.variable,
          playfair.variable,
        )}
      >
        <Provider>
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          {children}
          <Toaster closeButton />
        </Provider>
      </body>
    </html>
  )
}
